### PR TITLE
Update branches for DevX repositories

### PR DESCRIPTION
**Pull request by jfsoul**
## What does this change?
Adds branch specifications for DevX repos as part of a trial to enable batching update PRs together. We now target a non-default branch and aggregate updates on a schedule into a single PR.

### CODE REVIEW

**Review by jacobwinch — APPROVED** [review]

**Comment by rtyley** [comment]
Merging this PR coincides with the Scala Steward job failing!

image

It fails [while trying to find sbt dependencies for Amigo](https://github.com/guardian/scala-steward-public-repos/runs/7669625385?check_suite_focus=true#step:5:179), complaining about `BuildInfoKey.constant`.

The Scala Steward run seems to continue for the other repos, but as there's one failure (for Amigo), the entire run is reported as a fail (and I get an automated failure email from ci_activity@noreply.github.com, does anyone else get these?).

I see that Amigo's [dependency-updates](https://github.com/guardian/amigo/commits/dependency-updates) branch has [an update to `sbt-buildinfo`](https://github.com/guardian/amigo/commit/22e3807fddfd99450ec948e5160a5ab939bf251a), which probably caused this fail:

image

...I guess normally we would see a CI failure on the Scala Steward PR in _Amigo_, but the run of the Scala Steward Action creating the PRs would pass, because it would be using the `main` branch to run sbt and work out the dependencies? But it can't do that here, because it's now pointing to the `dependency-update` branch, which has a broken sbt definition due to the sbt-buildinfo update?

**Comment by jfsoul** [comment]
Thanks for spotting that @rtyley, unfortunately notifications for schedule-triggered actions go to the last person to edit the schedule, so I think you're the only one receiving these notifications at the moment!

As for Amigo causing the job to fail - I think your analysis is correct. It's a result of my decision in our experiments to not run CI for individual dependency updates that only end up in the `dependency-updates` branch. The idea is that we merge blindly and then review/fix in-aggregate in a single PR targeting `main`.

I believe that we only see this kind of failure when the build definition is invalid, which I hope will be relatively rare (compared to compilation errors, or updates that require no changes.) My evidence for this is that I've fixed the issue with the build definition in https://github.com/guardian/amigo/commit/db0518bd5d5a04fd5def7e4d73c388c0fb5c7772, which has made the Scala Steward run green, despite there being compile errors in Amigo on that branch.

So I think our options are:
1. Do nothing and hope that build definition errors are relatively rare. There's a danger that these kinds of failures of the Scala Steward job eventually cause us to miss genuine problems.
2. Run CI of some kind on every PR before merging (I viewed this as a bit of a waste of resources, but maybe this is justification enough)
3. Decentralise Scala Steward so that failures like this are at least local to the project that caused them

I think my inclination would be to start with 1. and proceed to 2. if failures become a regular occurrence. What do you think?

**Comment by rtyley** [comment]
> I think my inclination would be to start with 1. and proceed to 2. if failures become a regular occurrence. What do you think?

Happy enough to go for 1. for now, but if it happens again can we switch to 2. ?

I see that _not_ running the CI is what's currently [recommended](https://github.com/guardian/.github/blob/c0dd3f98eeb28c50bf4cfe70dae57f9a676406ee/.github/workflows/docs/pr-batching.md?plain=1#L37), but I think personally I'd like to have the CI running for PRs on public repos at least, where we're not paying for the GitHub Action minutes, right?!

**Comment by jfsoul** [comment]
Sounds good, I'm quite happy to switch to recommending CI, but it would also be informative to get a feel for the current workflow before changing it.

**Comment by jfsoul** [comment]
FYI I'll look into the new failures @rtyley

**Comment by jfsoul** [comment]
@rtyley On the change to running CI on every PR; I'm trying it out at the moment. Unfortunately making CI checks compulsory before merging is not as simple as I thought, because adding that branch protection rule prevents us from [automatically keeping](https://github.com/guardian/.github/blob/9486581b0ab327e9cf955dfca827bd44e6ad02c3/.github/workflows/pr-batching_tracking-branch.yml#L40) the `dependency-update` branch up to date with changes from `main`. So we can run CI, which will make it easier to spot problematic PRs, but I can't see a simple way to prevent errors from appearing in this repo's action from time to time.

**Pull request merged**
